// Code generated by running "go generate". DO NOT EDIT.

// Copyright 2025 The Wuffs Authors.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

package lowleveljpeg

// UpsampleFrom produces one 16×16 quad-block from one 8×8 block.
//
// It uses a triangle filter.
func (dst *QuadBlockU8) UpsampleFrom(src *BlockU8) {
	if (dst == nil) || (src == nil) {
		return
	}
	dst[0x00] = src[0x00]
	dst[0x01] = uint8(((3 * uint32(src[0x00])) + uint32(src[0x01]) + 2) / 4)
	dst[0x02] = uint8(((3 * uint32(src[0x01])) + uint32(src[0x00]) + 2) / 4)
	dst[0x03] = uint8(((3 * uint32(src[0x01])) + uint32(src[0x02]) + 2) / 4)
	dst[0x04] = uint8(((3 * uint32(src[0x02])) + uint32(src[0x01]) + 2) / 4)
	dst[0x05] = uint8(((3 * uint32(src[0x02])) + uint32(src[0x03]) + 2) / 4)
	dst[0x06] = uint8(((3 * uint32(src[0x03])) + uint32(src[0x02]) + 2) / 4)
	dst[0x07] = uint8(((3 * uint32(src[0x03])) + uint32(src[0x04]) + 2) / 4)
	dst[0x08] = uint8(((3 * uint32(src[0x04])) + uint32(src[0x03]) + 2) / 4)
	dst[0x09] = uint8(((3 * uint32(src[0x04])) + uint32(src[0x05]) + 2) / 4)
	dst[0x0A] = uint8(((3 * uint32(src[0x05])) + uint32(src[0x04]) + 2) / 4)
	dst[0x0B] = uint8(((3 * uint32(src[0x05])) + uint32(src[0x06]) + 2) / 4)
	dst[0x0C] = uint8(((3 * uint32(src[0x06])) + uint32(src[0x05]) + 2) / 4)
	dst[0x0D] = uint8(((3 * uint32(src[0x06])) + uint32(src[0x07]) + 2) / 4)
	dst[0x0E] = uint8(((3 * uint32(src[0x07])) + uint32(src[0x06]) + 2) / 4)
	dst[0x0F] = src[0x07]
	dst[0x10] = uint8(((3 * uint32(src[0x00])) + uint32(src[0x08]) + 2) / 4)
	dst[0x11] = uint8(((9 * uint32(src[0x00])) + (3 * uint32(src[0x01])) + (3 * uint32(src[0x08])) + uint32(src[0x09]) + 8) / 16)
	dst[0x12] = uint8(((9 * uint32(src[0x01])) + (3 * uint32(src[0x00])) + (3 * uint32(src[0x09])) + uint32(src[0x08]) + 8) / 16)
	dst[0x13] = uint8(((9 * uint32(src[0x01])) + (3 * uint32(src[0x02])) + (3 * uint32(src[0x09])) + uint32(src[0x0A]) + 8) / 16)
	dst[0x14] = uint8(((9 * uint32(src[0x02])) + (3 * uint32(src[0x01])) + (3 * uint32(src[0x0A])) + uint32(src[0x09]) + 8) / 16)
	dst[0x15] = uint8(((9 * uint32(src[0x02])) + (3 * uint32(src[0x03])) + (3 * uint32(src[0x0A])) + uint32(src[0x0B]) + 8) / 16)
	dst[0x16] = uint8(((9 * uint32(src[0x03])) + (3 * uint32(src[0x02])) + (3 * uint32(src[0x0B])) + uint32(src[0x0A]) + 8) / 16)
	dst[0x17] = uint8(((9 * uint32(src[0x03])) + (3 * uint32(src[0x04])) + (3 * uint32(src[0x0B])) + uint32(src[0x0C]) + 8) / 16)
	dst[0x18] = uint8(((9 * uint32(src[0x04])) + (3 * uint32(src[0x03])) + (3 * uint32(src[0x0C])) + uint32(src[0x0B]) + 8) / 16)
	dst[0x19] = uint8(((9 * uint32(src[0x04])) + (3 * uint32(src[0x05])) + (3 * uint32(src[0x0C])) + uint32(src[0x0D]) + 8) / 16)
	dst[0x1A] = uint8(((9 * uint32(src[0x05])) + (3 * uint32(src[0x04])) + (3 * uint32(src[0x0D])) + uint32(src[0x0C]) + 8) / 16)
	dst[0x1B] = uint8(((9 * uint32(src[0x05])) + (3 * uint32(src[0x06])) + (3 * uint32(src[0x0D])) + uint32(src[0x0E]) + 8) / 16)
	dst[0x1C] = uint8(((9 * uint32(src[0x06])) + (3 * uint32(src[0x05])) + (3 * uint32(src[0x0E])) + uint32(src[0x0D]) + 8) / 16)
	dst[0x1D] = uint8(((9 * uint32(src[0x06])) + (3 * uint32(src[0x07])) + (3 * uint32(src[0x0E])) + uint32(src[0x0F]) + 8) / 16)
	dst[0x1E] = uint8(((9 * uint32(src[0x07])) + (3 * uint32(src[0x06])) + (3 * uint32(src[0x0F])) + uint32(src[0x0E]) + 8) / 16)
	dst[0x1F] = uint8(((3 * uint32(src[0x07])) + uint32(src[0x0F]) + 2) / 4)
	dst[0x20] = uint8(((3 * uint32(src[0x08])) + uint32(src[0x00]) + 2) / 4)
	dst[0x21] = uint8(((9 * uint32(src[0x08])) + (3 * uint32(src[0x09])) + (3 * uint32(src[0x00])) + uint32(src[0x01]) + 8) / 16)
	dst[0x22] = uint8(((9 * uint32(src[0x09])) + (3 * uint32(src[0x08])) + (3 * uint32(src[0x01])) + uint32(src[0x00]) + 8) / 16)
	dst[0x23] = uint8(((9 * uint32(src[0x09])) + (3 * uint32(src[0x0A])) + (3 * uint32(src[0x01])) + uint32(src[0x02]) + 8) / 16)
	dst[0x24] = uint8(((9 * uint32(src[0x0A])) + (3 * uint32(src[0x09])) + (3 * uint32(src[0x02])) + uint32(src[0x01]) + 8) / 16)
	dst[0x25] = uint8(((9 * uint32(src[0x0A])) + (3 * uint32(src[0x0B])) + (3 * uint32(src[0x02])) + uint32(src[0x03]) + 8) / 16)
	dst[0x26] = uint8(((9 * uint32(src[0x0B])) + (3 * uint32(src[0x0A])) + (3 * uint32(src[0x03])) + uint32(src[0x02]) + 8) / 16)
	dst[0x27] = uint8(((9 * uint32(src[0x0B])) + (3 * uint32(src[0x0C])) + (3 * uint32(src[0x03])) + uint32(src[0x04]) + 8) / 16)
	dst[0x28] = uint8(((9 * uint32(src[0x0C])) + (3 * uint32(src[0x0B])) + (3 * uint32(src[0x04])) + uint32(src[0x03]) + 8) / 16)
	dst[0x29] = uint8(((9 * uint32(src[0x0C])) + (3 * uint32(src[0x0D])) + (3 * uint32(src[0x04])) + uint32(src[0x05]) + 8) / 16)
	dst[0x2A] = uint8(((9 * uint32(src[0x0D])) + (3 * uint32(src[0x0C])) + (3 * uint32(src[0x05])) + uint32(src[0x04]) + 8) / 16)
	dst[0x2B] = uint8(((9 * uint32(src[0x0D])) + (3 * uint32(src[0x0E])) + (3 * uint32(src[0x05])) + uint32(src[0x06]) + 8) / 16)
	dst[0x2C] = uint8(((9 * uint32(src[0x0E])) + (3 * uint32(src[0x0D])) + (3 * uint32(src[0x06])) + uint32(src[0x05]) + 8) / 16)
	dst[0x2D] = uint8(((9 * uint32(src[0x0E])) + (3 * uint32(src[0x0F])) + (3 * uint32(src[0x06])) + uint32(src[0x07]) + 8) / 16)
	dst[0x2E] = uint8(((9 * uint32(src[0x0F])) + (3 * uint32(src[0x0E])) + (3 * uint32(src[0x07])) + uint32(src[0x06]) + 8) / 16)
	dst[0x2F] = uint8(((3 * uint32(src[0x0F])) + uint32(src[0x07]) + 2) / 4)
	dst[0x30] = uint8(((3 * uint32(src[0x08])) + uint32(src[0x10]) + 2) / 4)
	dst[0x31] = uint8(((9 * uint32(src[0x08])) + (3 * uint32(src[0x09])) + (3 * uint32(src[0x10])) + uint32(src[0x11]) + 8) / 16)
	dst[0x32] = uint8(((9 * uint32(src[0x09])) + (3 * uint32(src[0x08])) + (3 * uint32(src[0x11])) + uint32(src[0x10]) + 8) / 16)
	dst[0x33] = uint8(((9 * uint32(src[0x09])) + (3 * uint32(src[0x0A])) + (3 * uint32(src[0x11])) + uint32(src[0x12]) + 8) / 16)
	dst[0x34] = uint8(((9 * uint32(src[0x0A])) + (3 * uint32(src[0x09])) + (3 * uint32(src[0x12])) + uint32(src[0x11]) + 8) / 16)
	dst[0x35] = uint8(((9 * uint32(src[0x0A])) + (3 * uint32(src[0x0B])) + (3 * uint32(src[0x12])) + uint32(src[0x13]) + 8) / 16)
	dst[0x36] = uint8(((9 * uint32(src[0x0B])) + (3 * uint32(src[0x0A])) + (3 * uint32(src[0x13])) + uint32(src[0x12]) + 8) / 16)
	dst[0x37] = uint8(((9 * uint32(src[0x0B])) + (3 * uint32(src[0x0C])) + (3 * uint32(src[0x13])) + uint32(src[0x14]) + 8) / 16)
	dst[0x38] = uint8(((9 * uint32(src[0x0C])) + (3 * uint32(src[0x0B])) + (3 * uint32(src[0x14])) + uint32(src[0x13]) + 8) / 16)
	dst[0x39] = uint8(((9 * uint32(src[0x0C])) + (3 * uint32(src[0x0D])) + (3 * uint32(src[0x14])) + uint32(src[0x15]) + 8) / 16)
	dst[0x3A] = uint8(((9 * uint32(src[0x0D])) + (3 * uint32(src[0x0C])) + (3 * uint32(src[0x15])) + uint32(src[0x14]) + 8) / 16)
	dst[0x3B] = uint8(((9 * uint32(src[0x0D])) + (3 * uint32(src[0x0E])) + (3 * uint32(src[0x15])) + uint32(src[0x16]) + 8) / 16)
	dst[0x3C] = uint8(((9 * uint32(src[0x0E])) + (3 * uint32(src[0x0D])) + (3 * uint32(src[0x16])) + uint32(src[0x15]) + 8) / 16)
	dst[0x3D] = uint8(((9 * uint32(src[0x0E])) + (3 * uint32(src[0x0F])) + (3 * uint32(src[0x16])) + uint32(src[0x17]) + 8) / 16)
	dst[0x3E] = uint8(((9 * uint32(src[0x0F])) + (3 * uint32(src[0x0E])) + (3 * uint32(src[0x17])) + uint32(src[0x16]) + 8) / 16)
	dst[0x3F] = uint8(((3 * uint32(src[0x0F])) + uint32(src[0x17]) + 2) / 4)
	dst[0x40] = uint8(((3 * uint32(src[0x10])) + uint32(src[0x08]) + 2) / 4)
	dst[0x41] = uint8(((9 * uint32(src[0x10])) + (3 * uint32(src[0x11])) + (3 * uint32(src[0x08])) + uint32(src[0x09]) + 8) / 16)
	dst[0x42] = uint8(((9 * uint32(src[0x11])) + (3 * uint32(src[0x10])) + (3 * uint32(src[0x09])) + uint32(src[0x08]) + 8) / 16)
	dst[0x43] = uint8(((9 * uint32(src[0x11])) + (3 * uint32(src[0x12])) + (3 * uint32(src[0x09])) + uint32(src[0x0A]) + 8) / 16)
	dst[0x44] = uint8(((9 * uint32(src[0x12])) + (3 * uint32(src[0x11])) + (3 * uint32(src[0x0A])) + uint32(src[0x09]) + 8) / 16)
	dst[0x45] = uint8(((9 * uint32(src[0x12])) + (3 * uint32(src[0x13])) + (3 * uint32(src[0x0A])) + uint32(src[0x0B]) + 8) / 16)
	dst[0x46] = uint8(((9 * uint32(src[0x13])) + (3 * uint32(src[0x12])) + (3 * uint32(src[0x0B])) + uint32(src[0x0A]) + 8) / 16)
	dst[0x47] = uint8(((9 * uint32(src[0x13])) + (3 * uint32(src[0x14])) + (3 * uint32(src[0x0B])) + uint32(src[0x0C]) + 8) / 16)
	dst[0x48] = uint8(((9 * uint32(src[0x14])) + (3 * uint32(src[0x13])) + (3 * uint32(src[0x0C])) + uint32(src[0x0B]) + 8) / 16)
	dst[0x49] = uint8(((9 * uint32(src[0x14])) + (3 * uint32(src[0x15])) + (3 * uint32(src[0x0C])) + uint32(src[0x0D]) + 8) / 16)
	dst[0x4A] = uint8(((9 * uint32(src[0x15])) + (3 * uint32(src[0x14])) + (3 * uint32(src[0x0D])) + uint32(src[0x0C]) + 8) / 16)
	dst[0x4B] = uint8(((9 * uint32(src[0x15])) + (3 * uint32(src[0x16])) + (3 * uint32(src[0x0D])) + uint32(src[0x0E]) + 8) / 16)
	dst[0x4C] = uint8(((9 * uint32(src[0x16])) + (3 * uint32(src[0x15])) + (3 * uint32(src[0x0E])) + uint32(src[0x0D]) + 8) / 16)
	dst[0x4D] = uint8(((9 * uint32(src[0x16])) + (3 * uint32(src[0x17])) + (3 * uint32(src[0x0E])) + uint32(src[0x0F]) + 8) / 16)
	dst[0x4E] = uint8(((9 * uint32(src[0x17])) + (3 * uint32(src[0x16])) + (3 * uint32(src[0x0F])) + uint32(src[0x0E]) + 8) / 16)
	dst[0x4F] = uint8(((3 * uint32(src[0x17])) + uint32(src[0x0F]) + 2) / 4)
	dst[0x50] = uint8(((3 * uint32(src[0x10])) + uint32(src[0x18]) + 2) / 4)
	dst[0x51] = uint8(((9 * uint32(src[0x10])) + (3 * uint32(src[0x11])) + (3 * uint32(src[0x18])) + uint32(src[0x19]) + 8) / 16)
	dst[0x52] = uint8(((9 * uint32(src[0x11])) + (3 * uint32(src[0x10])) + (3 * uint32(src[0x19])) + uint32(src[0x18]) + 8) / 16)
	dst[0x53] = uint8(((9 * uint32(src[0x11])) + (3 * uint32(src[0x12])) + (3 * uint32(src[0x19])) + uint32(src[0x1A]) + 8) / 16)
	dst[0x54] = uint8(((9 * uint32(src[0x12])) + (3 * uint32(src[0x11])) + (3 * uint32(src[0x1A])) + uint32(src[0x19]) + 8) / 16)
	dst[0x55] = uint8(((9 * uint32(src[0x12])) + (3 * uint32(src[0x13])) + (3 * uint32(src[0x1A])) + uint32(src[0x1B]) + 8) / 16)
	dst[0x56] = uint8(((9 * uint32(src[0x13])) + (3 * uint32(src[0x12])) + (3 * uint32(src[0x1B])) + uint32(src[0x1A]) + 8) / 16)
	dst[0x57] = uint8(((9 * uint32(src[0x13])) + (3 * uint32(src[0x14])) + (3 * uint32(src[0x1B])) + uint32(src[0x1C]) + 8) / 16)
	dst[0x58] = uint8(((9 * uint32(src[0x14])) + (3 * uint32(src[0x13])) + (3 * uint32(src[0x1C])) + uint32(src[0x1B]) + 8) / 16)
	dst[0x59] = uint8(((9 * uint32(src[0x14])) + (3 * uint32(src[0x15])) + (3 * uint32(src[0x1C])) + uint32(src[0x1D]) + 8) / 16)
	dst[0x5A] = uint8(((9 * uint32(src[0x15])) + (3 * uint32(src[0x14])) + (3 * uint32(src[0x1D])) + uint32(src[0x1C]) + 8) / 16)
	dst[0x5B] = uint8(((9 * uint32(src[0x15])) + (3 * uint32(src[0x16])) + (3 * uint32(src[0x1D])) + uint32(src[0x1E]) + 8) / 16)
	dst[0x5C] = uint8(((9 * uint32(src[0x16])) + (3 * uint32(src[0x15])) + (3 * uint32(src[0x1E])) + uint32(src[0x1D]) + 8) / 16)
	dst[0x5D] = uint8(((9 * uint32(src[0x16])) + (3 * uint32(src[0x17])) + (3 * uint32(src[0x1E])) + uint32(src[0x1F]) + 8) / 16)
	dst[0x5E] = uint8(((9 * uint32(src[0x17])) + (3 * uint32(src[0x16])) + (3 * uint32(src[0x1F])) + uint32(src[0x1E]) + 8) / 16)
	dst[0x5F] = uint8(((3 * uint32(src[0x17])) + uint32(src[0x1F]) + 2) / 4)
	dst[0x60] = uint8(((3 * uint32(src[0x18])) + uint32(src[0x10]) + 2) / 4)
	dst[0x61] = uint8(((9 * uint32(src[0x18])) + (3 * uint32(src[0x19])) + (3 * uint32(src[0x10])) + uint32(src[0x11]) + 8) / 16)
	dst[0x62] = uint8(((9 * uint32(src[0x19])) + (3 * uint32(src[0x18])) + (3 * uint32(src[0x11])) + uint32(src[0x10]) + 8) / 16)
	dst[0x63] = uint8(((9 * uint32(src[0x19])) + (3 * uint32(src[0x1A])) + (3 * uint32(src[0x11])) + uint32(src[0x12]) + 8) / 16)
	dst[0x64] = uint8(((9 * uint32(src[0x1A])) + (3 * uint32(src[0x19])) + (3 * uint32(src[0x12])) + uint32(src[0x11]) + 8) / 16)
	dst[0x65] = uint8(((9 * uint32(src[0x1A])) + (3 * uint32(src[0x1B])) + (3 * uint32(src[0x12])) + uint32(src[0x13]) + 8) / 16)
	dst[0x66] = uint8(((9 * uint32(src[0x1B])) + (3 * uint32(src[0x1A])) + (3 * uint32(src[0x13])) + uint32(src[0x12]) + 8) / 16)
	dst[0x67] = uint8(((9 * uint32(src[0x1B])) + (3 * uint32(src[0x1C])) + (3 * uint32(src[0x13])) + uint32(src[0x14]) + 8) / 16)
	dst[0x68] = uint8(((9 * uint32(src[0x1C])) + (3 * uint32(src[0x1B])) + (3 * uint32(src[0x14])) + uint32(src[0x13]) + 8) / 16)
	dst[0x69] = uint8(((9 * uint32(src[0x1C])) + (3 * uint32(src[0x1D])) + (3 * uint32(src[0x14])) + uint32(src[0x15]) + 8) / 16)
	dst[0x6A] = uint8(((9 * uint32(src[0x1D])) + (3 * uint32(src[0x1C])) + (3 * uint32(src[0x15])) + uint32(src[0x14]) + 8) / 16)
	dst[0x6B] = uint8(((9 * uint32(src[0x1D])) + (3 * uint32(src[0x1E])) + (3 * uint32(src[0x15])) + uint32(src[0x16]) + 8) / 16)
	dst[0x6C] = uint8(((9 * uint32(src[0x1E])) + (3 * uint32(src[0x1D])) + (3 * uint32(src[0x16])) + uint32(src[0x15]) + 8) / 16)
	dst[0x6D] = uint8(((9 * uint32(src[0x1E])) + (3 * uint32(src[0x1F])) + (3 * uint32(src[0x16])) + uint32(src[0x17]) + 8) / 16)
	dst[0x6E] = uint8(((9 * uint32(src[0x1F])) + (3 * uint32(src[0x1E])) + (3 * uint32(src[0x17])) + uint32(src[0x16]) + 8) / 16)
	dst[0x6F] = uint8(((3 * uint32(src[0x1F])) + uint32(src[0x17]) + 2) / 4)
	dst[0x70] = uint8(((3 * uint32(src[0x18])) + uint32(src[0x20]) + 2) / 4)
	dst[0x71] = uint8(((9 * uint32(src[0x18])) + (3 * uint32(src[0x19])) + (3 * uint32(src[0x20])) + uint32(src[0x21]) + 8) / 16)
	dst[0x72] = uint8(((9 * uint32(src[0x19])) + (3 * uint32(src[0x18])) + (3 * uint32(src[0x21])) + uint32(src[0x20]) + 8) / 16)
	dst[0x73] = uint8(((9 * uint32(src[0x19])) + (3 * uint32(src[0x1A])) + (3 * uint32(src[0x21])) + uint32(src[0x22]) + 8) / 16)
	dst[0x74] = uint8(((9 * uint32(src[0x1A])) + (3 * uint32(src[0x19])) + (3 * uint32(src[0x22])) + uint32(src[0x21]) + 8) / 16)
	dst[0x75] = uint8(((9 * uint32(src[0x1A])) + (3 * uint32(src[0x1B])) + (3 * uint32(src[0x22])) + uint32(src[0x23]) + 8) / 16)
	dst[0x76] = uint8(((9 * uint32(src[0x1B])) + (3 * uint32(src[0x1A])) + (3 * uint32(src[0x23])) + uint32(src[0x22]) + 8) / 16)
	dst[0x77] = uint8(((9 * uint32(src[0x1B])) + (3 * uint32(src[0x1C])) + (3 * uint32(src[0x23])) + uint32(src[0x24]) + 8) / 16)
	dst[0x78] = uint8(((9 * uint32(src[0x1C])) + (3 * uint32(src[0x1B])) + (3 * uint32(src[0x24])) + uint32(src[0x23]) + 8) / 16)
	dst[0x79] = uint8(((9 * uint32(src[0x1C])) + (3 * uint32(src[0x1D])) + (3 * uint32(src[0x24])) + uint32(src[0x25]) + 8) / 16)
	dst[0x7A] = uint8(((9 * uint32(src[0x1D])) + (3 * uint32(src[0x1C])) + (3 * uint32(src[0x25])) + uint32(src[0x24]) + 8) / 16)
	dst[0x7B] = uint8(((9 * uint32(src[0x1D])) + (3 * uint32(src[0x1E])) + (3 * uint32(src[0x25])) + uint32(src[0x26]) + 8) / 16)
	dst[0x7C] = uint8(((9 * uint32(src[0x1E])) + (3 * uint32(src[0x1D])) + (3 * uint32(src[0x26])) + uint32(src[0x25]) + 8) / 16)
	dst[0x7D] = uint8(((9 * uint32(src[0x1E])) + (3 * uint32(src[0x1F])) + (3 * uint32(src[0x26])) + uint32(src[0x27]) + 8) / 16)
	dst[0x7E] = uint8(((9 * uint32(src[0x1F])) + (3 * uint32(src[0x1E])) + (3 * uint32(src[0x27])) + uint32(src[0x26]) + 8) / 16)
	dst[0x7F] = uint8(((3 * uint32(src[0x1F])) + uint32(src[0x27]) + 2) / 4)
	dst[0x80] = uint8(((3 * uint32(src[0x20])) + uint32(src[0x18]) + 2) / 4)
	dst[0x81] = uint8(((9 * uint32(src[0x20])) + (3 * uint32(src[0x21])) + (3 * uint32(src[0x18])) + uint32(src[0x19]) + 8) / 16)
	dst[0x82] = uint8(((9 * uint32(src[0x21])) + (3 * uint32(src[0x20])) + (3 * uint32(src[0x19])) + uint32(src[0x18]) + 8) / 16)
	dst[0x83] = uint8(((9 * uint32(src[0x21])) + (3 * uint32(src[0x22])) + (3 * uint32(src[0x19])) + uint32(src[0x1A]) + 8) / 16)
	dst[0x84] = uint8(((9 * uint32(src[0x22])) + (3 * uint32(src[0x21])) + (3 * uint32(src[0x1A])) + uint32(src[0x19]) + 8) / 16)
	dst[0x85] = uint8(((9 * uint32(src[0x22])) + (3 * uint32(src[0x23])) + (3 * uint32(src[0x1A])) + uint32(src[0x1B]) + 8) / 16)
	dst[0x86] = uint8(((9 * uint32(src[0x23])) + (3 * uint32(src[0x22])) + (3 * uint32(src[0x1B])) + uint32(src[0x1A]) + 8) / 16)
	dst[0x87] = uint8(((9 * uint32(src[0x23])) + (3 * uint32(src[0x24])) + (3 * uint32(src[0x1B])) + uint32(src[0x1C]) + 8) / 16)
	dst[0x88] = uint8(((9 * uint32(src[0x24])) + (3 * uint32(src[0x23])) + (3 * uint32(src[0x1C])) + uint32(src[0x1B]) + 8) / 16)
	dst[0x89] = uint8(((9 * uint32(src[0x24])) + (3 * uint32(src[0x25])) + (3 * uint32(src[0x1C])) + uint32(src[0x1D]) + 8) / 16)
	dst[0x8A] = uint8(((9 * uint32(src[0x25])) + (3 * uint32(src[0x24])) + (3 * uint32(src[0x1D])) + uint32(src[0x1C]) + 8) / 16)
	dst[0x8B] = uint8(((9 * uint32(src[0x25])) + (3 * uint32(src[0x26])) + (3 * uint32(src[0x1D])) + uint32(src[0x1E]) + 8) / 16)
	dst[0x8C] = uint8(((9 * uint32(src[0x26])) + (3 * uint32(src[0x25])) + (3 * uint32(src[0x1E])) + uint32(src[0x1D]) + 8) / 16)
	dst[0x8D] = uint8(((9 * uint32(src[0x26])) + (3 * uint32(src[0x27])) + (3 * uint32(src[0x1E])) + uint32(src[0x1F]) + 8) / 16)
	dst[0x8E] = uint8(((9 * uint32(src[0x27])) + (3 * uint32(src[0x26])) + (3 * uint32(src[0x1F])) + uint32(src[0x1E]) + 8) / 16)
	dst[0x8F] = uint8(((3 * uint32(src[0x27])) + uint32(src[0x1F]) + 2) / 4)
	dst[0x90] = uint8(((3 * uint32(src[0x20])) + uint32(src[0x28]) + 2) / 4)
	dst[0x91] = uint8(((9 * uint32(src[0x20])) + (3 * uint32(src[0x21])) + (3 * uint32(src[0x28])) + uint32(src[0x29]) + 8) / 16)
	dst[0x92] = uint8(((9 * uint32(src[0x21])) + (3 * uint32(src[0x20])) + (3 * uint32(src[0x29])) + uint32(src[0x28]) + 8) / 16)
	dst[0x93] = uint8(((9 * uint32(src[0x21])) + (3 * uint32(src[0x22])) + (3 * uint32(src[0x29])) + uint32(src[0x2A]) + 8) / 16)
	dst[0x94] = uint8(((9 * uint32(src[0x22])) + (3 * uint32(src[0x21])) + (3 * uint32(src[0x2A])) + uint32(src[0x29]) + 8) / 16)
	dst[0x95] = uint8(((9 * uint32(src[0x22])) + (3 * uint32(src[0x23])) + (3 * uint32(src[0x2A])) + uint32(src[0x2B]) + 8) / 16)
	dst[0x96] = uint8(((9 * uint32(src[0x23])) + (3 * uint32(src[0x22])) + (3 * uint32(src[0x2B])) + uint32(src[0x2A]) + 8) / 16)
	dst[0x97] = uint8(((9 * uint32(src[0x23])) + (3 * uint32(src[0x24])) + (3 * uint32(src[0x2B])) + uint32(src[0x2C]) + 8) / 16)
	dst[0x98] = uint8(((9 * uint32(src[0x24])) + (3 * uint32(src[0x23])) + (3 * uint32(src[0x2C])) + uint32(src[0x2B]) + 8) / 16)
	dst[0x99] = uint8(((9 * uint32(src[0x24])) + (3 * uint32(src[0x25])) + (3 * uint32(src[0x2C])) + uint32(src[0x2D]) + 8) / 16)
	dst[0x9A] = uint8(((9 * uint32(src[0x25])) + (3 * uint32(src[0x24])) + (3 * uint32(src[0x2D])) + uint32(src[0x2C]) + 8) / 16)
	dst[0x9B] = uint8(((9 * uint32(src[0x25])) + (3 * uint32(src[0x26])) + (3 * uint32(src[0x2D])) + uint32(src[0x2E]) + 8) / 16)
	dst[0x9C] = uint8(((9 * uint32(src[0x26])) + (3 * uint32(src[0x25])) + (3 * uint32(src[0x2E])) + uint32(src[0x2D]) + 8) / 16)
	dst[0x9D] = uint8(((9 * uint32(src[0x26])) + (3 * uint32(src[0x27])) + (3 * uint32(src[0x2E])) + uint32(src[0x2F]) + 8) / 16)
	dst[0x9E] = uint8(((9 * uint32(src[0x27])) + (3 * uint32(src[0x26])) + (3 * uint32(src[0x2F])) + uint32(src[0x2E]) + 8) / 16)
	dst[0x9F] = uint8(((3 * uint32(src[0x27])) + uint32(src[0x2F]) + 2) / 4)
	dst[0xA0] = uint8(((3 * uint32(src[0x28])) + uint32(src[0x20]) + 2) / 4)
	dst[0xA1] = uint8(((9 * uint32(src[0x28])) + (3 * uint32(src[0x29])) + (3 * uint32(src[0x20])) + uint32(src[0x21]) + 8) / 16)
	dst[0xA2] = uint8(((9 * uint32(src[0x29])) + (3 * uint32(src[0x28])) + (3 * uint32(src[0x21])) + uint32(src[0x20]) + 8) / 16)
	dst[0xA3] = uint8(((9 * uint32(src[0x29])) + (3 * uint32(src[0x2A])) + (3 * uint32(src[0x21])) + uint32(src[0x22]) + 8) / 16)
	dst[0xA4] = uint8(((9 * uint32(src[0x2A])) + (3 * uint32(src[0x29])) + (3 * uint32(src[0x22])) + uint32(src[0x21]) + 8) / 16)
	dst[0xA5] = uint8(((9 * uint32(src[0x2A])) + (3 * uint32(src[0x2B])) + (3 * uint32(src[0x22])) + uint32(src[0x23]) + 8) / 16)
	dst[0xA6] = uint8(((9 * uint32(src[0x2B])) + (3 * uint32(src[0x2A])) + (3 * uint32(src[0x23])) + uint32(src[0x22]) + 8) / 16)
	dst[0xA7] = uint8(((9 * uint32(src[0x2B])) + (3 * uint32(src[0x2C])) + (3 * uint32(src[0x23])) + uint32(src[0x24]) + 8) / 16)
	dst[0xA8] = uint8(((9 * uint32(src[0x2C])) + (3 * uint32(src[0x2B])) + (3 * uint32(src[0x24])) + uint32(src[0x23]) + 8) / 16)
	dst[0xA9] = uint8(((9 * uint32(src[0x2C])) + (3 * uint32(src[0x2D])) + (3 * uint32(src[0x24])) + uint32(src[0x25]) + 8) / 16)
	dst[0xAA] = uint8(((9 * uint32(src[0x2D])) + (3 * uint32(src[0x2C])) + (3 * uint32(src[0x25])) + uint32(src[0x24]) + 8) / 16)
	dst[0xAB] = uint8(((9 * uint32(src[0x2D])) + (3 * uint32(src[0x2E])) + (3 * uint32(src[0x25])) + uint32(src[0x26]) + 8) / 16)
	dst[0xAC] = uint8(((9 * uint32(src[0x2E])) + (3 * uint32(src[0x2D])) + (3 * uint32(src[0x26])) + uint32(src[0x25]) + 8) / 16)
	dst[0xAD] = uint8(((9 * uint32(src[0x2E])) + (3 * uint32(src[0x2F])) + (3 * uint32(src[0x26])) + uint32(src[0x27]) + 8) / 16)
	dst[0xAE] = uint8(((9 * uint32(src[0x2F])) + (3 * uint32(src[0x2E])) + (3 * uint32(src[0x27])) + uint32(src[0x26]) + 8) / 16)
	dst[0xAF] = uint8(((3 * uint32(src[0x2F])) + uint32(src[0x27]) + 2) / 4)
	dst[0xB0] = uint8(((3 * uint32(src[0x28])) + uint32(src[0x30]) + 2) / 4)
	dst[0xB1] = uint8(((9 * uint32(src[0x28])) + (3 * uint32(src[0x29])) + (3 * uint32(src[0x30])) + uint32(src[0x31]) + 8) / 16)
	dst[0xB2] = uint8(((9 * uint32(src[0x29])) + (3 * uint32(src[0x28])) + (3 * uint32(src[0x31])) + uint32(src[0x30]) + 8) / 16)
	dst[0xB3] = uint8(((9 * uint32(src[0x29])) + (3 * uint32(src[0x2A])) + (3 * uint32(src[0x31])) + uint32(src[0x32]) + 8) / 16)
	dst[0xB4] = uint8(((9 * uint32(src[0x2A])) + (3 * uint32(src[0x29])) + (3 * uint32(src[0x32])) + uint32(src[0x31]) + 8) / 16)
	dst[0xB5] = uint8(((9 * uint32(src[0x2A])) + (3 * uint32(src[0x2B])) + (3 * uint32(src[0x32])) + uint32(src[0x33]) + 8) / 16)
	dst[0xB6] = uint8(((9 * uint32(src[0x2B])) + (3 * uint32(src[0x2A])) + (3 * uint32(src[0x33])) + uint32(src[0x32]) + 8) / 16)
	dst[0xB7] = uint8(((9 * uint32(src[0x2B])) + (3 * uint32(src[0x2C])) + (3 * uint32(src[0x33])) + uint32(src[0x34]) + 8) / 16)
	dst[0xB8] = uint8(((9 * uint32(src[0x2C])) + (3 * uint32(src[0x2B])) + (3 * uint32(src[0x34])) + uint32(src[0x33]) + 8) / 16)
	dst[0xB9] = uint8(((9 * uint32(src[0x2C])) + (3 * uint32(src[0x2D])) + (3 * uint32(src[0x34])) + uint32(src[0x35]) + 8) / 16)
	dst[0xBA] = uint8(((9 * uint32(src[0x2D])) + (3 * uint32(src[0x2C])) + (3 * uint32(src[0x35])) + uint32(src[0x34]) + 8) / 16)
	dst[0xBB] = uint8(((9 * uint32(src[0x2D])) + (3 * uint32(src[0x2E])) + (3 * uint32(src[0x35])) + uint32(src[0x36]) + 8) / 16)
	dst[0xBC] = uint8(((9 * uint32(src[0x2E])) + (3 * uint32(src[0x2D])) + (3 * uint32(src[0x36])) + uint32(src[0x35]) + 8) / 16)
	dst[0xBD] = uint8(((9 * uint32(src[0x2E])) + (3 * uint32(src[0x2F])) + (3 * uint32(src[0x36])) + uint32(src[0x37]) + 8) / 16)
	dst[0xBE] = uint8(((9 * uint32(src[0x2F])) + (3 * uint32(src[0x2E])) + (3 * uint32(src[0x37])) + uint32(src[0x36]) + 8) / 16)
	dst[0xBF] = uint8(((3 * uint32(src[0x2F])) + uint32(src[0x37]) + 2) / 4)
	dst[0xC0] = uint8(((3 * uint32(src[0x30])) + uint32(src[0x28]) + 2) / 4)
	dst[0xC1] = uint8(((9 * uint32(src[0x30])) + (3 * uint32(src[0x31])) + (3 * uint32(src[0x28])) + uint32(src[0x29]) + 8) / 16)
	dst[0xC2] = uint8(((9 * uint32(src[0x31])) + (3 * uint32(src[0x30])) + (3 * uint32(src[0x29])) + uint32(src[0x28]) + 8) / 16)
	dst[0xC3] = uint8(((9 * uint32(src[0x31])) + (3 * uint32(src[0x32])) + (3 * uint32(src[0x29])) + uint32(src[0x2A]) + 8) / 16)
	dst[0xC4] = uint8(((9 * uint32(src[0x32])) + (3 * uint32(src[0x31])) + (3 * uint32(src[0x2A])) + uint32(src[0x29]) + 8) / 16)
	dst[0xC5] = uint8(((9 * uint32(src[0x32])) + (3 * uint32(src[0x33])) + (3 * uint32(src[0x2A])) + uint32(src[0x2B]) + 8) / 16)
	dst[0xC6] = uint8(((9 * uint32(src[0x33])) + (3 * uint32(src[0x32])) + (3 * uint32(src[0x2B])) + uint32(src[0x2A]) + 8) / 16)
	dst[0xC7] = uint8(((9 * uint32(src[0x33])) + (3 * uint32(src[0x34])) + (3 * uint32(src[0x2B])) + uint32(src[0x2C]) + 8) / 16)
	dst[0xC8] = uint8(((9 * uint32(src[0x34])) + (3 * uint32(src[0x33])) + (3 * uint32(src[0x2C])) + uint32(src[0x2B]) + 8) / 16)
	dst[0xC9] = uint8(((9 * uint32(src[0x34])) + (3 * uint32(src[0x35])) + (3 * uint32(src[0x2C])) + uint32(src[0x2D]) + 8) / 16)
	dst[0xCA] = uint8(((9 * uint32(src[0x35])) + (3 * uint32(src[0x34])) + (3 * uint32(src[0x2D])) + uint32(src[0x2C]) + 8) / 16)
	dst[0xCB] = uint8(((9 * uint32(src[0x35])) + (3 * uint32(src[0x36])) + (3 * uint32(src[0x2D])) + uint32(src[0x2E]) + 8) / 16)
	dst[0xCC] = uint8(((9 * uint32(src[0x36])) + (3 * uint32(src[0x35])) + (3 * uint32(src[0x2E])) + uint32(src[0x2D]) + 8) / 16)
	dst[0xCD] = uint8(((9 * uint32(src[0x36])) + (3 * uint32(src[0x37])) + (3 * uint32(src[0x2E])) + uint32(src[0x2F]) + 8) / 16)
	dst[0xCE] = uint8(((9 * uint32(src[0x37])) + (3 * uint32(src[0x36])) + (3 * uint32(src[0x2F])) + uint32(src[0x2E]) + 8) / 16)
	dst[0xCF] = uint8(((3 * uint32(src[0x37])) + uint32(src[0x2F]) + 2) / 4)
	dst[0xD0] = uint8(((3 * uint32(src[0x30])) + uint32(src[0x38]) + 2) / 4)
	dst[0xD1] = uint8(((9 * uint32(src[0x30])) + (3 * uint32(src[0x31])) + (3 * uint32(src[0x38])) + uint32(src[0x39]) + 8) / 16)
	dst[0xD2] = uint8(((9 * uint32(src[0x31])) + (3 * uint32(src[0x30])) + (3 * uint32(src[0x39])) + uint32(src[0x38]) + 8) / 16)
	dst[0xD3] = uint8(((9 * uint32(src[0x31])) + (3 * uint32(src[0x32])) + (3 * uint32(src[0x39])) + uint32(src[0x3A]) + 8) / 16)
	dst[0xD4] = uint8(((9 * uint32(src[0x32])) + (3 * uint32(src[0x31])) + (3 * uint32(src[0x3A])) + uint32(src[0x39]) + 8) / 16)
	dst[0xD5] = uint8(((9 * uint32(src[0x32])) + (3 * uint32(src[0x33])) + (3 * uint32(src[0x3A])) + uint32(src[0x3B]) + 8) / 16)
	dst[0xD6] = uint8(((9 * uint32(src[0x33])) + (3 * uint32(src[0x32])) + (3 * uint32(src[0x3B])) + uint32(src[0x3A]) + 8) / 16)
	dst[0xD7] = uint8(((9 * uint32(src[0x33])) + (3 * uint32(src[0x34])) + (3 * uint32(src[0x3B])) + uint32(src[0x3C]) + 8) / 16)
	dst[0xD8] = uint8(((9 * uint32(src[0x34])) + (3 * uint32(src[0x33])) + (3 * uint32(src[0x3C])) + uint32(src[0x3B]) + 8) / 16)
	dst[0xD9] = uint8(((9 * uint32(src[0x34])) + (3 * uint32(src[0x35])) + (3 * uint32(src[0x3C])) + uint32(src[0x3D]) + 8) / 16)
	dst[0xDA] = uint8(((9 * uint32(src[0x35])) + (3 * uint32(src[0x34])) + (3 * uint32(src[0x3D])) + uint32(src[0x3C]) + 8) / 16)
	dst[0xDB] = uint8(((9 * uint32(src[0x35])) + (3 * uint32(src[0x36])) + (3 * uint32(src[0x3D])) + uint32(src[0x3E]) + 8) / 16)
	dst[0xDC] = uint8(((9 * uint32(src[0x36])) + (3 * uint32(src[0x35])) + (3 * uint32(src[0x3E])) + uint32(src[0x3D]) + 8) / 16)
	dst[0xDD] = uint8(((9 * uint32(src[0x36])) + (3 * uint32(src[0x37])) + (3 * uint32(src[0x3E])) + uint32(src[0x3F]) + 8) / 16)
	dst[0xDE] = uint8(((9 * uint32(src[0x37])) + (3 * uint32(src[0x36])) + (3 * uint32(src[0x3F])) + uint32(src[0x3E]) + 8) / 16)
	dst[0xDF] = uint8(((3 * uint32(src[0x37])) + uint32(src[0x3F]) + 2) / 4)
	dst[0xE0] = uint8(((3 * uint32(src[0x38])) + uint32(src[0x30]) + 2) / 4)
	dst[0xE1] = uint8(((9 * uint32(src[0x38])) + (3 * uint32(src[0x39])) + (3 * uint32(src[0x30])) + uint32(src[0x31]) + 8) / 16)
	dst[0xE2] = uint8(((9 * uint32(src[0x39])) + (3 * uint32(src[0x38])) + (3 * uint32(src[0x31])) + uint32(src[0x30]) + 8) / 16)
	dst[0xE3] = uint8(((9 * uint32(src[0x39])) + (3 * uint32(src[0x3A])) + (3 * uint32(src[0x31])) + uint32(src[0x32]) + 8) / 16)
	dst[0xE4] = uint8(((9 * uint32(src[0x3A])) + (3 * uint32(src[0x39])) + (3 * uint32(src[0x32])) + uint32(src[0x31]) + 8) / 16)
	dst[0xE5] = uint8(((9 * uint32(src[0x3A])) + (3 * uint32(src[0x3B])) + (3 * uint32(src[0x32])) + uint32(src[0x33]) + 8) / 16)
	dst[0xE6] = uint8(((9 * uint32(src[0x3B])) + (3 * uint32(src[0x3A])) + (3 * uint32(src[0x33])) + uint32(src[0x32]) + 8) / 16)
	dst[0xE7] = uint8(((9 * uint32(src[0x3B])) + (3 * uint32(src[0x3C])) + (3 * uint32(src[0x33])) + uint32(src[0x34]) + 8) / 16)
	dst[0xE8] = uint8(((9 * uint32(src[0x3C])) + (3 * uint32(src[0x3B])) + (3 * uint32(src[0x34])) + uint32(src[0x33]) + 8) / 16)
	dst[0xE9] = uint8(((9 * uint32(src[0x3C])) + (3 * uint32(src[0x3D])) + (3 * uint32(src[0x34])) + uint32(src[0x35]) + 8) / 16)
	dst[0xEA] = uint8(((9 * uint32(src[0x3D])) + (3 * uint32(src[0x3C])) + (3 * uint32(src[0x35])) + uint32(src[0x34]) + 8) / 16)
	dst[0xEB] = uint8(((9 * uint32(src[0x3D])) + (3 * uint32(src[0x3E])) + (3 * uint32(src[0x35])) + uint32(src[0x36]) + 8) / 16)
	dst[0xEC] = uint8(((9 * uint32(src[0x3E])) + (3 * uint32(src[0x3D])) + (3 * uint32(src[0x36])) + uint32(src[0x35]) + 8) / 16)
	dst[0xED] = uint8(((9 * uint32(src[0x3E])) + (3 * uint32(src[0x3F])) + (3 * uint32(src[0x36])) + uint32(src[0x37]) + 8) / 16)
	dst[0xEE] = uint8(((9 * uint32(src[0x3F])) + (3 * uint32(src[0x3E])) + (3 * uint32(src[0x37])) + uint32(src[0x36]) + 8) / 16)
	dst[0xEF] = uint8(((3 * uint32(src[0x3F])) + uint32(src[0x37]) + 2) / 4)
	dst[0xF0] = src[0x38]
	dst[0xF1] = uint8(((3 * uint32(src[0x38])) + uint32(src[0x39]) + 2) / 4)
	dst[0xF2] = uint8(((3 * uint32(src[0x39])) + uint32(src[0x38]) + 2) / 4)
	dst[0xF3] = uint8(((3 * uint32(src[0x39])) + uint32(src[0x3A]) + 2) / 4)
	dst[0xF4] = uint8(((3 * uint32(src[0x3A])) + uint32(src[0x39]) + 2) / 4)
	dst[0xF5] = uint8(((3 * uint32(src[0x3A])) + uint32(src[0x3B]) + 2) / 4)
	dst[0xF6] = uint8(((3 * uint32(src[0x3B])) + uint32(src[0x3A]) + 2) / 4)
	dst[0xF7] = uint8(((3 * uint32(src[0x3B])) + uint32(src[0x3C]) + 2) / 4)
	dst[0xF8] = uint8(((3 * uint32(src[0x3C])) + uint32(src[0x3B]) + 2) / 4)
	dst[0xF9] = uint8(((3 * uint32(src[0x3C])) + uint32(src[0x3D]) + 2) / 4)
	dst[0xFA] = uint8(((3 * uint32(src[0x3D])) + uint32(src[0x3C]) + 2) / 4)
	dst[0xFB] = uint8(((3 * uint32(src[0x3D])) + uint32(src[0x3E]) + 2) / 4)
	dst[0xFC] = uint8(((3 * uint32(src[0x3E])) + uint32(src[0x3D]) + 2) / 4)
	dst[0xFD] = uint8(((3 * uint32(src[0x3E])) + uint32(src[0x3F]) + 2) / 4)
	dst[0xFE] = uint8(((3 * uint32(src[0x3F])) + uint32(src[0x3E]) + 2) / 4)
	dst[0xFF] = src[0x3F]
}

const hardCodedDHTSegments = "" +
	// 212 bytes for the first DHT segment.
	"\xFF\xC4\x00\xD2\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0A" +
	"\x0B\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00" +
	"\x01\x7D\x01\x02\x03\x00\x04\x11\x05\x12\x21\x31\x41\x06\x13\x51" +
	"\x61\x07\x22\x71\x14\x32\x81\x91\xA1\x08\x23\x42\xB1\xC1\x15\x52" +
	"\xD1\xF0\x24\x33\x62\x72\x82\x09\x0A\x16\x17\x18\x19\x1A\x25\x26" +
	"\x27\x28\x29\x2A\x34\x35\x36\x37\x38\x39\x3A\x43\x44\x45\x46\x47" +
	"\x48\x49\x4A\x53\x54\x55\x56\x57\x58\x59\x5A\x63\x64\x65\x66\x67" +
	"\x68\x69\x6A\x73\x74\x75\x76\x77\x78\x79\x7A\x83\x84\x85\x86\x87" +
	"\x88\x89\x8A\x92\x93\x94\x95\x96\x97\x98\x99\x9A\xA2\xA3\xA4\xA5" +
	"\xA6\xA7\xA8\xA9\xAA\xB2\xB3\xB4\xB5\xB6\xB7\xB8\xB9\xBA\xC2\xC3" +
	"\xC4\xC5\xC6\xC7\xC8\xC9\xCA\xD2\xD3\xD4\xD5\xD6\xD7\xD8\xD9\xDA" +
	"\xE1\xE2\xE3\xE4\xE5\xE6\xE7\xE8\xE9\xEA\xF1\xF2\xF3\xF4\xF5\xF6" +
	"\xF7\xF8\xF9\xFA" +
	// 212 bytes for the second DHT segment.
	"\xFF\xC4\x00\xD2\x01\x00\x03\x01\x01\x01\x01\x01\x01\x01\x01\x01" +
	"\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0A" +
	"\x0B\x11\x00\x02\x01\x02\x04\x04\x03\x04\x07\x05\x04\x04\x00\x01" +
	"\x02\x77\x00\x01\x02\x03\x11\x04\x05\x21\x31\x06\x12\x41\x51\x07" +
	"\x61\x71\x13\x22\x32\x81\x08\x14\x42\x91\xA1\xB1\xC1\x09\x23\x33" +
	"\x52\xF0\x15\x62\x72\xD1\x0A\x16\x24\x34\xE1\x25\xF1\x17\x18\x19" +
	"\x1A\x26\x27\x28\x29\x2A\x35\x36\x37\x38\x39\x3A\x43\x44\x45\x46" +
	"\x47\x48\x49\x4A\x53\x54\x55\x56\x57\x58\x59\x5A\x63\x64\x65\x66" +
	"\x67\x68\x69\x6A\x73\x74\x75\x76\x77\x78\x79\x7A\x82\x83\x84\x85" +
	"\x86\x87\x88\x89\x8A\x92\x93\x94\x95\x96\x97\x98\x99\x9A\xA2\xA3" +
	"\xA4\xA5\xA6\xA7\xA8\xA9\xAA\xB2\xB3\xB4\xB5\xB6\xB7\xB8\xB9\xBA" +
	"\xC2\xC3\xC4\xC5\xC6\xC7\xC8\xC9\xCA\xD2\xD3\xD4\xD5\xD6\xD7\xD8" +
	"\xD9\xDA\xE2\xE3\xE4\xE5\xE6\xE7\xE8\xE9\xEA\xF2\xF3\xF4\xF5\xF6" +
	"\xF7\xF8\xF9\xFA"

// huffmanBitWriter is a Huffman code LUT (Look-Up Table) for encoding.
//
// huffmanBitWriter[i] is the Huffman encoding for the value i: two uint16
// halves packed as a uint32. The low half holds the bitstring bits. The high
// half holds the bitstring length. Bitstrings are also known as code words.
//
// For example, huffmanBitWriters[0][5] being 0x00030006 means the Luma DC
// value 5 has the bitstring "110".
type huffmanBitWriter [256]uint32

var huffmanBitWriters = [4]huffmanBitWriter{{
	0x00020000, 0x00030002, 0x00030003, 0x00030004, 0x00030005, 0x00030006, 0x0004000E, 0x0005001E,
	0x0006003E, 0x0007007E, 0x000800FE, 0x000901FE, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
}, {
	0x0004000A, 0x00020000, 0x00020001, 0x00030004, 0x0004000B, 0x0005001A, 0x00070078, 0x000800F8,
	0x000A03F6, 0x0010FF82, 0x0010FF83, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0004000C, 0x0005001B, 0x00070079, 0x000901F6, 0x000B07F6, 0x0010FF84, 0x0010FF85,
	0x0010FF86, 0x0010FF87, 0x0010FF88, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0005001C, 0x000800F9, 0x000A03F7, 0x000C0FF4, 0x0010FF89, 0x0010FF8A, 0x0010FF8B,
	0x0010FF8C, 0x0010FF8D, 0x0010FF8E, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0006003A, 0x000901F7, 0x000C0FF5, 0x0010FF8F, 0x0010FF90, 0x0010FF91, 0x0010FF92,
	0x0010FF93, 0x0010FF94, 0x0010FF95, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0006003B, 0x000A03F8, 0x0010FF96, 0x0010FF97, 0x0010FF98, 0x0010FF99, 0x0010FF9A,
	0x0010FF9B, 0x0010FF9C, 0x0010FF9D, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0007007A, 0x000B07F7, 0x0010FF9E, 0x0010FF9F, 0x0010FFA0, 0x0010FFA1, 0x0010FFA2,
	0x0010FFA3, 0x0010FFA4, 0x0010FFA5, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0007007B, 0x000C0FF6, 0x0010FFA6, 0x0010FFA7, 0x0010FFA8, 0x0010FFA9, 0x0010FFAA,
	0x0010FFAB, 0x0010FFAC, 0x0010FFAD, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000800FA, 0x000C0FF7, 0x0010FFAE, 0x0010FFAF, 0x0010FFB0, 0x0010FFB1, 0x0010FFB2,
	0x0010FFB3, 0x0010FFB4, 0x0010FFB5, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000901F8, 0x000F7FC0, 0x0010FFB6, 0x0010FFB7, 0x0010FFB8, 0x0010FFB9, 0x0010FFBA,
	0x0010FFBB, 0x0010FFBC, 0x0010FFBD, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000901F9, 0x0010FFBE, 0x0010FFBF, 0x0010FFC0, 0x0010FFC1, 0x0010FFC2, 0x0010FFC3,
	0x0010FFC4, 0x0010FFC5, 0x0010FFC6, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000901FA, 0x0010FFC7, 0x0010FFC8, 0x0010FFC9, 0x0010FFCA, 0x0010FFCB, 0x0010FFCC,
	0x0010FFCD, 0x0010FFCE, 0x0010FFCF, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000A03F9, 0x0010FFD0, 0x0010FFD1, 0x0010FFD2, 0x0010FFD3, 0x0010FFD4, 0x0010FFD5,
	0x0010FFD6, 0x0010FFD7, 0x0010FFD8, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000A03FA, 0x0010FFD9, 0x0010FFDA, 0x0010FFDB, 0x0010FFDC, 0x0010FFDD, 0x0010FFDE,
	0x0010FFDF, 0x0010FFE0, 0x0010FFE1, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000B07F8, 0x0010FFE2, 0x0010FFE3, 0x0010FFE4, 0x0010FFE5, 0x0010FFE6, 0x0010FFE7,
	0x0010FFE8, 0x0010FFE9, 0x0010FFEA, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0010FFEB, 0x0010FFEC, 0x0010FFED, 0x0010FFEE, 0x0010FFEF, 0x0010FFF0, 0x0010FFF1,
	0x0010FFF2, 0x0010FFF3, 0x0010FFF4, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x000B07F9, 0x0010FFF5, 0x0010FFF6, 0x0010FFF7, 0x0010FFF8, 0x0010FFF9, 0x0010FFFA, 0x0010FFFB,
	0x0010FFFC, 0x0010FFFD, 0x0010FFFE, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
}, {
	0x00020000, 0x00020001, 0x00020002, 0x00030006, 0x0004000E, 0x0005001E, 0x0006003E, 0x0007007E,
	0x000800FE, 0x000901FE, 0x000A03FE, 0x000B07FE, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
}, {
	0x00020000, 0x00020001, 0x00030004, 0x0004000A, 0x00050018, 0x00050019, 0x00060038, 0x00070078,
	0x000901F4, 0x000A03F6, 0x000C0FF4, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0004000B, 0x00060039, 0x000800F6, 0x000901F5, 0x000B07F6, 0x000C0FF5, 0x0010FF88,
	0x0010FF89, 0x0010FF8A, 0x0010FF8B, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0005001A, 0x000800F7, 0x000A03F7, 0x000C0FF6, 0x000F7FC2, 0x0010FF8C, 0x0010FF8D,
	0x0010FF8E, 0x0010FF8F, 0x0010FF90, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0005001B, 0x000800F8, 0x000A03F8, 0x000C0FF7, 0x0010FF91, 0x0010FF92, 0x0010FF93,
	0x0010FF94, 0x0010FF95, 0x0010FF96, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0006003A, 0x000901F6, 0x0010FF97, 0x0010FF98, 0x0010FF99, 0x0010FF9A, 0x0010FF9B,
	0x0010FF9C, 0x0010FF9D, 0x0010FF9E, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0006003B, 0x000A03F9, 0x0010FF9F, 0x0010FFA0, 0x0010FFA1, 0x0010FFA2, 0x0010FFA3,
	0x0010FFA4, 0x0010FFA5, 0x0010FFA6, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00070079, 0x000B07F7, 0x0010FFA7, 0x0010FFA8, 0x0010FFA9, 0x0010FFAA, 0x0010FFAB,
	0x0010FFAC, 0x0010FFAD, 0x0010FFAE, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x0007007A, 0x000B07F8, 0x0010FFAF, 0x0010FFB0, 0x0010FFB1, 0x0010FFB2, 0x0010FFB3,
	0x0010FFB4, 0x0010FFB5, 0x0010FFB6, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000800F9, 0x0010FFB7, 0x0010FFB8, 0x0010FFB9, 0x0010FFBA, 0x0010FFBB, 0x0010FFBC,
	0x0010FFBD, 0x0010FFBE, 0x0010FFBF, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000901F7, 0x0010FFC0, 0x0010FFC1, 0x0010FFC2, 0x0010FFC3, 0x0010FFC4, 0x0010FFC5,
	0x0010FFC6, 0x0010FFC7, 0x0010FFC8, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000901F8, 0x0010FFC9, 0x0010FFCA, 0x0010FFCB, 0x0010FFCC, 0x0010FFCD, 0x0010FFCE,
	0x0010FFCF, 0x0010FFD0, 0x0010FFD1, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000901F9, 0x0010FFD2, 0x0010FFD3, 0x0010FFD4, 0x0010FFD5, 0x0010FFD6, 0x0010FFD7,
	0x0010FFD8, 0x0010FFD9, 0x0010FFDA, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000901FA, 0x0010FFDB, 0x0010FFDC, 0x0010FFDD, 0x0010FFDE, 0x0010FFDF, 0x0010FFE0,
	0x0010FFE1, 0x0010FFE2, 0x0010FFE3, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000B07F9, 0x0010FFE4, 0x0010FFE5, 0x0010FFE6, 0x0010FFE7, 0x0010FFE8, 0x0010FFE9,
	0x0010FFEA, 0x0010FFEB, 0x0010FFEC, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x000E3FE0, 0x0010FFED, 0x0010FFEE, 0x0010FFEF, 0x0010FFF0, 0x0010FFF1, 0x0010FFF2,
	0x0010FFF3, 0x0010FFF4, 0x0010FFF5, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x000A03FA, 0x000F7FC3, 0x0010FFF6, 0x0010FFF7, 0x0010FFF8, 0x0010FFF9, 0x0010FFFA, 0x0010FFFB,
	0x0010FFFC, 0x0010FFFD, 0x0010FFFE, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
}}
